#!/bin/sh

build() { 
	add_binary bash
	add_module overlay
	add_module loop
	add_binary rsync
	add_binary unsquashfs
	add_binary mksquashfs
	add_module vfat
	add_runscript
}

help() {
	cat << HELPEOF
Rollback compatibility for any filesystems and boot into squashfs file
HELPEOF
}
